on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  snyk_scan:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2

      - uses: snyk/actions/setup@master
      - run: snyk test


      
